domain: lichtausgang.github.io
url: https://lichtausgang.github.io
baseurl: "/"

title: Lichtausgang
email: leo@zfk-hb.de
author: Leo

lang: en

plugins:
  - jekyll-seo-tag

theme: wind-theme

color: "#13ccf9"
# disqus:
#   shortname: example-com
#
rrss:
  instagram: "https://www.instagram.com/lichtausgang"
